// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:money_manager/models.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(LoanModelAdapter());
    registerAdapter(TransactionModelAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(LoanModelAdapter());
    registerAdapter(TransactionModelAdapter());
  }
}
